import React from "react";
import { Text } from "@/components/ui/Text";
import { Button } from "@/components/ui/Button";

export function HeroSection() {
  return (
    <div className="flex flex-col gap-y-xs md:gap-y-xs text-left">
      <Text as="h1" variant="h1" className="text-primary">
        Prrrfct Cat brings play to every day.
      </Text>

      <Text as="h2" variant="h3" className="text-secondary">
        Caring for your AI-powered furry friend brings a relaxing moment of joy
        to your day.
      </Text>

      <Text as="p" variant="body-lg" className="text-tertiary">
        Create your own unique AI Cat—designed by you, generated by AI, and
        ready to bring some fun to your day. Take a quick break every day to
        care for your Cat and enjoy a moment of relaxation.
      </Text>

      <div>
        <Button
          variant="secondary"
          fullWidth
          aria-label="Watch demo"
        >
          Watch demo
        </Button>
      </div>
    </div>
  );
}
